server:
  port: 8081

spring:
  application:
    name: order-producer

  cloud:
    function:
      definition: orderSupplier

    stream:
      bindings:
        orderSupplier-out-0:
          destination: order-created-topic
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
